import { useState, useEffect, useCallback, Fragment } from 'react';
import { useRoutePermission } from '@/context/route-permission-context';
import { getAllRoutePermissions, updateRoutePermission } from '../api';
import { getRoles } from '@/features/roles/api';
import type { RoutePermission } from '../types';
import type { Role } from '@/features/roles/types';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Search, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import {
    Pagination,
    PaginationContent,
    PaginationEllipsis,
    PaginationItem,
    PaginationLink,
    PaginationNext,
    PaginationPrevious,
} from "@/components/ui/pagination";

interface RouteRoleMatrix {
    [routeKey: string]: {
        permission: RoutePermission;
        route_path: string;
        route_method: string;
        description: string;
        roles: { [roleName: string]: boolean };
    };
}

export default function RoutePermissionList() {
    const [permissions, setPermissions] = useState<RoutePermission[]>([]);
    const [roles, setRoles] = useState<Role[]>([]);
    const [matrix, setMatrix] = useState<RouteRoleMatrix>({});
    const [isLoading, setIsLoading] = useState(false);
    const [search, setSearch] = useState('');
    const [currentPage, setCurrentPage] = useState(1);
    const [perPage] = useState(20);
    const { refreshRules } = useRoutePermission();

    const fetchData = useCallback(async () => {
        try {
            setIsLoading(true);

            // Fetch all permissions generated by the backend route sync command.
            const routePermissions = await getAllRoutePermissions();
            setPermissions(routePermissions);

            // Fetch all roles
            const roleResponse = await getRoles({ per_page: 100 } as any);
            setRoles(roleResponse.data.filter(r => r.name !== 'admin')); // Exclude admin (always has access)

        } catch (error) {
            console.error('Failed to fetch data:', error);
            toast.error('Gagal mengambil data');
        } finally {
            setIsLoading(false);
        }
    }, []);

    useEffect(() => {
        fetchData();
    }, [fetchData]);

    // Build matrix when permissions or roles change
    useEffect(() => {
        if (roles.length === 0) return;

        const newMatrix: RouteRoleMatrix = {};

        // Route permissions are generated by the backend sync command from
        // registered Laravel routes. The frontend renders whatever exists in DB.
        permissions.forEach(perm => {
            const key = `${perm.route_method}:${perm.route_path}`;
            const roleStates: { [roleName: string]: boolean } = {};
            roles.forEach(role => {
                roleStates[role.name] = perm.allowed_roles?.includes(role.name) || false;
            });

            newMatrix[key] = {
                permission: perm,
                route_path: perm.route_path,
                route_method: perm.route_method,
                description: perm.description || '',
                roles: roleStates,
            };
        });

        setMatrix(newMatrix);
    }, [permissions, roles]);

    const handleCheckboxChange = async (routeKey: string, roleName: string, checked: boolean) => {
        // Immediately update UI matrix state so check/uncheck is completely instant and responsive
        setMatrix(prev => {
            const currentRoute = prev[routeKey];
            if (!currentRoute) return prev;

            return {
                ...prev,
                [routeKey]: {
                    ...currentRoute,
                    roles: {
                        ...currentRoute.roles,
                        [roleName]: checked,
                    },
                },
            };
        });

        // Background auto-save to database
        try {
            const routeData = matrix[routeKey];
            if (!routeData) return;

            // Gather all role names that are currently selected (including the new change)
            const allowedRoles = Object.entries({
                ...routeData.roles,
                [roleName]: checked,
            })
                .filter(([_, isAllowed]) => isAllowed)
                .map(([name]) => name);

            const formData = {
                route_path: routeData.route_path,
                route_method: routeData.route_method as any,
                description: routeData.description,
                allowed_roles: allowedRoles,
                is_active: true,
            };

            const toastId = toast.loading(`Menyimpan perubahan untuk ${routeData.route_method} ${routeData.route_path}...`);

            const updatedPermission = await updateRoutePermission({
                id: routeData.permission.id,
                data: formData
            });

            // Keep permission reference fresh in matrix state
            setMatrix(prev => ({
                ...prev,
                [routeKey]: {
                    ...prev[routeKey],
                    permission: updatedPermission,
                }
            }));

            toast.dismiss(toastId);
            toast.success(`Permission untuk ${routeData.route_method} ${routeData.route_path} berhasil diperbarui!`, {
                duration: 2000,
            });

            // Refresh permissions rules context
            refreshRules();

        } catch (error: any) {
            console.error('Failed to auto-save route permission:', error);
            
            // Revert UI state back to original checked value on failure
            setMatrix(prev => {
                const currentRoute = prev[routeKey];
                if (!currentRoute) return prev;

                return {
                    ...prev,
                    [routeKey]: {
                        ...currentRoute,
                        roles: {
                            ...currentRoute.roles,
                            [roleName]: !checked,
                        },
                    },
                };
            });

            const message = error?.data?.message || error?.message || 'Gagal menyimpan perubahan';
            toast.error(`Gagal menyimpan perubahan: ${message}`);
        }
    };

    const getMethodColor = (method: string) => {
        switch (method) {
            case 'GET': return 'bg-blue-100 text-blue-800';
            case 'POST': return 'bg-green-100 text-green-800';
            case 'PUT': return 'bg-yellow-100 text-yellow-800';
            case 'PATCH': return 'bg-orange-100 text-orange-800';
            case 'DELETE': return 'bg-red-100 text-red-800';
            default: return 'bg-gray-100 text-gray-800';
        }
    };

    // Filter matrix based on search
    const filteredMatrix = Object.entries(matrix).filter(([_, data]) =>
        data.route_path.toLowerCase().includes(search.toLowerCase()) ||
        data.description.toLowerCase().includes(search.toLowerCase())
    );

    // Pagination logic
    const totalItems = filteredMatrix.length;
    const totalPages = Math.ceil(totalItems / perPage);
    const paginatedMatrix = filteredMatrix.slice(
        (currentPage - 1) * perPage,
        currentPage * perPage
    );

    // Group by route path prefix
    const groupedRoutes = paginatedMatrix.reduce((acc, [key, data]) => {
        const prefix = data.route_path.split('/')[1] || 'other';
        if (!acc[prefix]) acc[prefix] = [];
        acc[prefix].push({ key, data });
        return acc;
    }, {} as Record<string, { key: string; data: RouteRoleMatrix[string] }[]>);

    if (isLoading) {
        return (
            <div className="flex items-center justify-center min-h-[400px]">
                <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold tracking-tight">Route Permissions</h1>
                    <p className="text-muted-foreground">
                        Centang role yang boleh mengakses setiap route hasil sinkronisasi backend. Admin selalu punya akses.
                    </p>
                </div>
            </div>

            <div className="flex items-center space-x-2">
                <div className="relative flex-1 max-w-sm">
                    <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                    <Input
                        placeholder="Cari route..."
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        className="pl-8"
                    />
                </div>
            </div>

            <div className="rounded-md border overflow-x-auto">
                <Table>
                    <TableHeader>
                        <TableRow className="bg-muted/50">
                            <TableHead className="w-[100px] sticky left-0 bg-muted/50">Method</TableHead>
                            <TableHead className="min-w-[250px] sticky left-[100px] bg-muted/50">Route Path</TableHead>
                            <TableHead className="min-w-[200px]">Deskripsi</TableHead>
                            {roles.map(role => (
                                <TableHead key={role.id} className="text-center w-[100px]">
                                    <div className="flex flex-col items-center gap-1">
                                        <span className="text-xs font-medium capitalize">{role.name}</span>
                                    </div>
                                </TableHead>
                            ))}
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {Object.entries(groupedRoutes).length === 0 ? (
                            <TableRow>
                                <TableCell colSpan={3 + roles.length} className="h-32 text-center text-muted-foreground">
                                    Tidak ada route permission. Jalankan sync route permission di backend terlebih dahulu.
                                </TableCell>
                            </TableRow>
                        ) : Object.entries(groupedRoutes).map(([group, routes]) => (
                            <Fragment key={`group-section-${group}`}>
                                <TableRow key={`group-header-${group}`} className="bg-muted/30">
                                    <TableCell colSpan={3 + roles.length} className="py-2">
                                        <span className="font-semibold text-sm uppercase tracking-wider text-muted-foreground">
                                            {group}
                                        </span>
                                    </TableCell>
                                </TableRow>
                                {routes.map(({ key, data }) => (
                                    <TableRow key={`route-${key}`} className="hover:bg-muted/20">
                                        <TableCell className="sticky left-0 bg-background">
                                            <Badge className={cn("text-xs", getMethodColor(data.route_method))}>
                                                {data.route_method}
                                            </Badge>
                                        </TableCell>
                                        <TableCell className="font-mono text-sm sticky left-[100px] bg-background">
                                            {data.route_path}
                                        </TableCell>
                                        <TableCell className="text-sm text-muted-foreground">
                                            {data.description}
                                        </TableCell>
                                        {roles.map(role => (
                                            <TableCell key={`role-${role.id}`} className="text-center">
                                                <Checkbox
                                                    checked={data.roles[role.name] || false}
                                                    onCheckedChange={(checked) =>
                                                        handleCheckboxChange(key, role.name, checked as boolean)
                                                    }
                                                    className="mx-auto"
                                                />
                                            </TableCell>
                                        ))}
                                    </TableRow>
                                ))}
                            </Fragment>
                        ))}
                    </TableBody>
                </Table>
            </div>

            {totalPages > 1 && (
                <div className="flex justify-center mt-4">
                    <Pagination>
                        <PaginationContent>
                            <PaginationItem>
                                <PaginationPrevious
                                    href="#"
                                    onClick={(e) => {
                                        e.preventDefault();
                                        if (currentPage > 1) setCurrentPage(currentPage - 1);
                                    }}
                                    className={currentPage === 1 ? 'pointer-events-none opacity-50' : 'cursor-pointer'}
                                />
                            </PaginationItem>

                            {(() => {
                                const items = [];
                                const maxVisiblePages = 5;

                                if (totalPages <= maxVisiblePages) {
                                    for (let i = 1; i <= totalPages; i++) items.push(i);
                                } else {
                                    if (currentPage <= 3) {
                                        for (let i = 1; i <= 3; i++) items.push(i);
                                        items.push('ellipsis');
                                        items.push(totalPages);
                                    } else if (currentPage >= totalPages - 2) {
                                        items.push(1);
                                        items.push('ellipsis');
                                        for (let i = totalPages - 2; i <= totalPages; i++) items.push(i);
                                    } else {
                                        items.push(1);
                                        items.push('ellipsis');
                                        items.push(currentPage - 1);
                                        items.push(currentPage);
                                        items.push(currentPage + 1);
                                        items.push('ellipsis');
                                        items.push(totalPages);
                                    }
                                }

                                return items.map((item, index) => (
                                    <PaginationItem key={index}>
                                        {item === 'ellipsis' ? (
                                            <PaginationEllipsis />
                                        ) : (
                                            <PaginationLink
                                                href="#"
                                                onClick={(e) => {
                                                    e.preventDefault();
                                                    setCurrentPage(item as number);
                                                }}
                                                isActive={currentPage === item}
                                                className="cursor-pointer"
                                            >
                                                {item}
                                            </PaginationLink>
                                        )}
                                    </PaginationItem>
                                ));
                            })()}

                            <PaginationItem>
                                <PaginationNext
                                    href="#"
                                    onClick={(e) => {
                                        e.preventDefault();
                                        if (currentPage < totalPages) setCurrentPage(currentPage + 1);
                                    }}
                                    className={currentPage === totalPages ? 'pointer-events-none opacity-50' : 'cursor-pointer'}
                                />
                            </PaginationItem>
                        </PaginationContent>
                    </Pagination>
                </div>
            )}
        </div>
    );
}
