/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRoutePermissionsIndexRouteImport } from './routes/_authenticated/route-permissions/index'
import { Route as AuthenticatedPenerimaIndexRouteImport } from './routes/_authenticated/penerima/index'
import { Route as AuthenticatedPekerjaanIndexRouteImport } from './routes/_authenticated/pekerjaan/index'
import { Route as AuthenticatedOutputIndexRouteImport } from './routes/_authenticated/output/index'
import { Route as AuthenticatedMenuPermissionsIndexRouteImport } from './routes/_authenticated/menu-permissions/index'
import { Route as AuthenticatedKontrakIndexRouteImport } from './routes/_authenticated/kontrak/index'
import { Route as AuthenticatedKegiatanIndexRouteImport } from './routes/_authenticated/kegiatan/index'
import { Route as AuthenticatedKecamatanIndexRouteImport } from './routes/_authenticated/kecamatan/index'
import { Route as AuthenticatedFotoIndexRouteImport } from './routes/_authenticated/foto/index'
import { Route as AuthenticatedDesaIndexRouteImport } from './routes/_authenticated/desa/index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticatedBerkasIndexRouteImport } from './routes/_authenticated/berkas/index'
import { Route as AuthenticatedUsersNewRouteImport } from './routes/_authenticated/users/new'
import { Route as AuthenticatedRoutePermissionsNewRouteImport } from './routes/_authenticated/route-permissions/new'
import { Route as AuthenticatedRolesNewRouteImport } from './routes/_authenticated/roles/new'
import { Route as AuthenticatedPermissionsNewRouteImport } from './routes/_authenticated/permissions/new'
import { Route as AuthenticatedPenerimaNewRouteImport } from './routes/_authenticated/penerima/new'
import { Route as AuthenticatedPekerjaanNewRouteImport } from './routes/_authenticated/pekerjaan/new'
import { Route as AuthenticatedPekerjaanIdRouteImport } from './routes/_authenticated/pekerjaan/$id'
import { Route as AuthenticatedOutputNewRouteImport } from './routes/_authenticated/output/new'
import { Route as AuthenticatedMenuPermissionsNewRouteImport } from './routes/_authenticated/menu-permissions/new'
import { Route as AuthenticatedKontrakNewRouteImport } from './routes/_authenticated/kontrak/new'
import { Route as AuthenticatedKegiatanNewRouteImport } from './routes/_authenticated/kegiatan/new'
import { Route as AuthenticatedKegiatanRoleNewRouteImport } from './routes/_authenticated/kegiatan-role/new'
import { Route as AuthenticatedKecamatanNewRouteImport } from './routes/_authenticated/kecamatan/new'
import { Route as AuthenticatedFotoNewRouteImport } from './routes/_authenticated/foto/new'
import { Route as AuthenticatedDesaNewRouteImport } from './routes/_authenticated/desa/new'
import { Route as AuthenticatedBerkasNewRouteImport } from './routes/_authenticated/berkas/new'
import { Route as AuthenticatedUsersIdEditRouteImport } from './routes/_authenticated/users/$id.edit'
import { Route as AuthenticatedRoutePermissionsIdEditRouteImport } from './routes/_authenticated/route-permissions/$id.edit'
import { Route as AuthenticatedRolesIdEditRouteImport } from './routes/_authenticated/roles/$id.edit'
import { Route as AuthenticatedPermissionsIdEditRouteImport } from './routes/_authenticated/permissions/$id.edit'
import { Route as AuthenticatedPenerimaIdEditRouteImport } from './routes/_authenticated/penerima/$id.edit'
import { Route as AuthenticatedPekerjaanIdProgressRouteImport } from './routes/_authenticated/pekerjaan/$id.progress'
import { Route as AuthenticatedPekerjaanIdEditRouteImport } from './routes/_authenticated/pekerjaan/$id.edit'
import { Route as AuthenticatedOutputIdEditRouteImport } from './routes/_authenticated/output/$id.edit'
import { Route as AuthenticatedMenuPermissionsIdEditRouteImport } from './routes/_authenticated/menu-permissions/$id.edit'
import { Route as AuthenticatedKontrakIdEditRouteImport } from './routes/_authenticated/kontrak/$id.edit'
import { Route as AuthenticatedKegiatanIdEditRouteImport } from './routes/_authenticated/kegiatan/$id.edit'
import { Route as AuthenticatedKegiatanRoleIdEditRouteImport } from './routes/_authenticated/kegiatan-role/$id.edit'
import { Route as AuthenticatedKecamatanIdEditRouteImport } from './routes/_authenticated/kecamatan/$id.edit'
import { Route as AuthenticatedFotoIdEditRouteImport } from './routes/_authenticated/foto/$id.edit'
import { Route as AuthenticatedDesaIdEditRouteImport } from './routes/_authenticated/desa/$id.edit'
import { Route as AuthenticatedBerkasIdEditRouteImport } from './routes/_authenticated/berkas/$id.edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoutePermissionsIndexRoute =
  AuthenticatedRoutePermissionsIndexRouteImport.update({
    id: '/route-permissions/',
    path: '/route-permissions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPenerimaIndexRoute =
  AuthenticatedPenerimaIndexRouteImport.update({
    id: '/penerima/',
    path: '/penerima/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPekerjaanIndexRoute =
  AuthenticatedPekerjaanIndexRouteImport.update({
    id: '/pekerjaan/',
    path: '/pekerjaan/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOutputIndexRoute =
  AuthenticatedOutputIndexRouteImport.update({
    id: '/output/',
    path: '/output/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMenuPermissionsIndexRoute =
  AuthenticatedMenuPermissionsIndexRouteImport.update({
    id: '/menu-permissions/',
    path: '/menu-permissions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKontrakIndexRoute =
  AuthenticatedKontrakIndexRouteImport.update({
    id: '/kontrak/',
    path: '/kontrak/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKegiatanIndexRoute =
  AuthenticatedKegiatanIndexRouteImport.update({
    id: '/kegiatan/',
    path: '/kegiatan/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKecamatanIndexRoute =
  AuthenticatedKecamatanIndexRouteImport.update({
    id: '/kecamatan/',
    path: '/kecamatan/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFotoIndexRoute = AuthenticatedFotoIndexRouteImport.update({
  id: '/foto/',
  path: '/foto/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDesaIndexRoute = AuthenticatedDesaIndexRouteImport.update({
  id: '/desa/',
  path: '/desa/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBerkasIndexRoute =
  AuthenticatedBerkasIndexRouteImport.update({
    id: '/berkas/',
    path: '/berkas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutePermissionsNewRoute =
  AuthenticatedRoutePermissionsNewRouteImport.update({
    id: '/route-permissions/new',
    path: '/route-permissions/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRolesNewRoute = AuthenticatedRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPermissionsNewRoute =
  AuthenticatedPermissionsNewRouteImport.update({
    id: '/permissions/new',
    path: '/permissions/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPenerimaNewRoute =
  AuthenticatedPenerimaNewRouteImport.update({
    id: '/penerima/new',
    path: '/penerima/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPekerjaanNewRoute =
  AuthenticatedPekerjaanNewRouteImport.update({
    id: '/pekerjaan/new',
    path: '/pekerjaan/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPekerjaanIdRoute =
  AuthenticatedPekerjaanIdRouteImport.update({
    id: '/pekerjaan/$id',
    path: '/pekerjaan/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOutputNewRoute = AuthenticatedOutputNewRouteImport.update({
  id: '/output/new',
  path: '/output/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMenuPermissionsNewRoute =
  AuthenticatedMenuPermissionsNewRouteImport.update({
    id: '/menu-permissions/new',
    path: '/menu-permissions/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKontrakNewRoute = AuthenticatedKontrakNewRouteImport.update({
  id: '/kontrak/new',
  path: '/kontrak/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKegiatanNewRoute =
  AuthenticatedKegiatanNewRouteImport.update({
    id: '/kegiatan/new',
    path: '/kegiatan/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKegiatanRoleNewRoute =
  AuthenticatedKegiatanRoleNewRouteImport.update({
    id: '/kegiatan-role/new',
    path: '/kegiatan-role/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKecamatanNewRoute =
  AuthenticatedKecamatanNewRouteImport.update({
    id: '/kecamatan/new',
    path: '/kecamatan/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFotoNewRoute = AuthenticatedFotoNewRouteImport.update({
  id: '/foto/new',
  path: '/foto/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDesaNewRoute = AuthenticatedDesaNewRouteImport.update({
  id: '/desa/new',
  path: '/desa/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBerkasNewRoute = AuthenticatedBerkasNewRouteImport.update({
  id: '/berkas/new',
  path: '/berkas/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIdEditRoute =
  AuthenticatedUsersIdEditRouteImport.update({
    id: '/users/$id/edit',
    path: '/users/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoutePermissionsIdEditRoute =
  AuthenticatedRoutePermissionsIdEditRouteImport.update({
    id: '/route-permissions/$id/edit',
    path: '/route-permissions/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRolesIdEditRoute =
  AuthenticatedRolesIdEditRouteImport.update({
    id: '/roles/$id/edit',
    path: '/roles/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPermissionsIdEditRoute =
  AuthenticatedPermissionsIdEditRouteImport.update({
    id: '/permissions/$id/edit',
    path: '/permissions/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPenerimaIdEditRoute =
  AuthenticatedPenerimaIdEditRouteImport.update({
    id: '/penerima/$id/edit',
    path: '/penerima/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPekerjaanIdProgressRoute =
  AuthenticatedPekerjaanIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedPekerjaanIdRoute,
  } as any)
const AuthenticatedPekerjaanIdEditRoute =
  AuthenticatedPekerjaanIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedPekerjaanIdRoute,
  } as any)
const AuthenticatedOutputIdEditRoute =
  AuthenticatedOutputIdEditRouteImport.update({
    id: '/output/$id/edit',
    path: '/output/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMenuPermissionsIdEditRoute =
  AuthenticatedMenuPermissionsIdEditRouteImport.update({
    id: '/menu-permissions/$id/edit',
    path: '/menu-permissions/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKontrakIdEditRoute =
  AuthenticatedKontrakIdEditRouteImport.update({
    id: '/kontrak/$id/edit',
    path: '/kontrak/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKegiatanIdEditRoute =
  AuthenticatedKegiatanIdEditRouteImport.update({
    id: '/kegiatan/$id/edit',
    path: '/kegiatan/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKegiatanRoleIdEditRoute =
  AuthenticatedKegiatanRoleIdEditRouteImport.update({
    id: '/kegiatan-role/$id/edit',
    path: '/kegiatan-role/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKecamatanIdEditRoute =
  AuthenticatedKecamatanIdEditRouteImport.update({
    id: '/kecamatan/$id/edit',
    path: '/kecamatan/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFotoIdEditRoute = AuthenticatedFotoIdEditRouteImport.update({
  id: '/foto/$id/edit',
  path: '/foto/$id/edit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDesaIdEditRoute = AuthenticatedDesaIdEditRouteImport.update({
  id: '/desa/$id/edit',
  path: '/desa/$id/edit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBerkasIdEditRoute =
  AuthenticatedBerkasIdEditRouteImport.update({
    id: '/berkas/$id/edit',
    path: '/berkas/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/oauth-callback': typeof OauthCallbackRoute
  '/sign-in': typeof SignInRoute
  '/': typeof AuthenticatedIndexRoute
  '/berkas/new': typeof AuthenticatedBerkasNewRoute
  '/desa/new': typeof AuthenticatedDesaNewRoute
  '/foto/new': typeof AuthenticatedFotoNewRoute
  '/kecamatan/new': typeof AuthenticatedKecamatanNewRoute
  '/kegiatan-role/new': typeof AuthenticatedKegiatanRoleNewRoute
  '/kegiatan/new': typeof AuthenticatedKegiatanNewRoute
  '/kontrak/new': typeof AuthenticatedKontrakNewRoute
  '/menu-permissions/new': typeof AuthenticatedMenuPermissionsNewRoute
  '/output/new': typeof AuthenticatedOutputNewRoute
  '/pekerjaan/$id': typeof AuthenticatedPekerjaanIdRouteWithChildren
  '/pekerjaan/new': typeof AuthenticatedPekerjaanNewRoute
  '/penerima/new': typeof AuthenticatedPenerimaNewRoute
  '/permissions/new': typeof AuthenticatedPermissionsNewRoute
  '/roles/new': typeof AuthenticatedRolesNewRoute
  '/route-permissions/new': typeof AuthenticatedRoutePermissionsNewRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/berkas': typeof AuthenticatedBerkasIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/desa': typeof AuthenticatedDesaIndexRoute
  '/foto': typeof AuthenticatedFotoIndexRoute
  '/kecamatan': typeof AuthenticatedKecamatanIndexRoute
  '/kegiatan': typeof AuthenticatedKegiatanIndexRoute
  '/kontrak': typeof AuthenticatedKontrakIndexRoute
  '/menu-permissions': typeof AuthenticatedMenuPermissionsIndexRoute
  '/output': typeof AuthenticatedOutputIndexRoute
  '/pekerjaan': typeof AuthenticatedPekerjaanIndexRoute
  '/penerima': typeof AuthenticatedPenerimaIndexRoute
  '/route-permissions': typeof AuthenticatedRoutePermissionsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/berkas/$id/edit': typeof AuthenticatedBerkasIdEditRoute
  '/desa/$id/edit': typeof AuthenticatedDesaIdEditRoute
  '/foto/$id/edit': typeof AuthenticatedFotoIdEditRoute
  '/kecamatan/$id/edit': typeof AuthenticatedKecamatanIdEditRoute
  '/kegiatan-role/$id/edit': typeof AuthenticatedKegiatanRoleIdEditRoute
  '/kegiatan/$id/edit': typeof AuthenticatedKegiatanIdEditRoute
  '/kontrak/$id/edit': typeof AuthenticatedKontrakIdEditRoute
  '/menu-permissions/$id/edit': typeof AuthenticatedMenuPermissionsIdEditRoute
  '/output/$id/edit': typeof AuthenticatedOutputIdEditRoute
  '/pekerjaan/$id/edit': typeof AuthenticatedPekerjaanIdEditRoute
  '/pekerjaan/$id/progress': typeof AuthenticatedPekerjaanIdProgressRoute
  '/penerima/$id/edit': typeof AuthenticatedPenerimaIdEditRoute
  '/permissions/$id/edit': typeof AuthenticatedPermissionsIdEditRoute
  '/roles/$id/edit': typeof AuthenticatedRolesIdEditRoute
  '/route-permissions/$id/edit': typeof AuthenticatedRoutePermissionsIdEditRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
}
export interface FileRoutesByTo {
  '/oauth-callback': typeof OauthCallbackRoute
  '/sign-in': typeof SignInRoute
  '/': typeof AuthenticatedIndexRoute
  '/berkas/new': typeof AuthenticatedBerkasNewRoute
  '/desa/new': typeof AuthenticatedDesaNewRoute
  '/foto/new': typeof AuthenticatedFotoNewRoute
  '/kecamatan/new': typeof AuthenticatedKecamatanNewRoute
  '/kegiatan-role/new': typeof AuthenticatedKegiatanRoleNewRoute
  '/kegiatan/new': typeof AuthenticatedKegiatanNewRoute
  '/kontrak/new': typeof AuthenticatedKontrakNewRoute
  '/menu-permissions/new': typeof AuthenticatedMenuPermissionsNewRoute
  '/output/new': typeof AuthenticatedOutputNewRoute
  '/pekerjaan/$id': typeof AuthenticatedPekerjaanIdRouteWithChildren
  '/pekerjaan/new': typeof AuthenticatedPekerjaanNewRoute
  '/penerima/new': typeof AuthenticatedPenerimaNewRoute
  '/permissions/new': typeof AuthenticatedPermissionsNewRoute
  '/roles/new': typeof AuthenticatedRolesNewRoute
  '/route-permissions/new': typeof AuthenticatedRoutePermissionsNewRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/berkas': typeof AuthenticatedBerkasIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/desa': typeof AuthenticatedDesaIndexRoute
  '/foto': typeof AuthenticatedFotoIndexRoute
  '/kecamatan': typeof AuthenticatedKecamatanIndexRoute
  '/kegiatan': typeof AuthenticatedKegiatanIndexRoute
  '/kontrak': typeof AuthenticatedKontrakIndexRoute
  '/menu-permissions': typeof AuthenticatedMenuPermissionsIndexRoute
  '/output': typeof AuthenticatedOutputIndexRoute
  '/pekerjaan': typeof AuthenticatedPekerjaanIndexRoute
  '/penerima': typeof AuthenticatedPenerimaIndexRoute
  '/route-permissions': typeof AuthenticatedRoutePermissionsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/berkas/$id/edit': typeof AuthenticatedBerkasIdEditRoute
  '/desa/$id/edit': typeof AuthenticatedDesaIdEditRoute
  '/foto/$id/edit': typeof AuthenticatedFotoIdEditRoute
  '/kecamatan/$id/edit': typeof AuthenticatedKecamatanIdEditRoute
  '/kegiatan-role/$id/edit': typeof AuthenticatedKegiatanRoleIdEditRoute
  '/kegiatan/$id/edit': typeof AuthenticatedKegiatanIdEditRoute
  '/kontrak/$id/edit': typeof AuthenticatedKontrakIdEditRoute
  '/menu-permissions/$id/edit': typeof AuthenticatedMenuPermissionsIdEditRoute
  '/output/$id/edit': typeof AuthenticatedOutputIdEditRoute
  '/pekerjaan/$id/edit': typeof AuthenticatedPekerjaanIdEditRoute
  '/pekerjaan/$id/progress': typeof AuthenticatedPekerjaanIdProgressRoute
  '/penerima/$id/edit': typeof AuthenticatedPenerimaIdEditRoute
  '/permissions/$id/edit': typeof AuthenticatedPermissionsIdEditRoute
  '/roles/$id/edit': typeof AuthenticatedRolesIdEditRoute
  '/route-permissions/$id/edit': typeof AuthenticatedRoutePermissionsIdEditRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/oauth-callback': typeof OauthCallbackRoute
  '/sign-in': typeof SignInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/berkas/new': typeof AuthenticatedBerkasNewRoute
  '/_authenticated/desa/new': typeof AuthenticatedDesaNewRoute
  '/_authenticated/foto/new': typeof AuthenticatedFotoNewRoute
  '/_authenticated/kecamatan/new': typeof AuthenticatedKecamatanNewRoute
  '/_authenticated/kegiatan-role/new': typeof AuthenticatedKegiatanRoleNewRoute
  '/_authenticated/kegiatan/new': typeof AuthenticatedKegiatanNewRoute
  '/_authenticated/kontrak/new': typeof AuthenticatedKontrakNewRoute
  '/_authenticated/menu-permissions/new': typeof AuthenticatedMenuPermissionsNewRoute
  '/_authenticated/output/new': typeof AuthenticatedOutputNewRoute
  '/_authenticated/pekerjaan/$id': typeof AuthenticatedPekerjaanIdRouteWithChildren
  '/_authenticated/pekerjaan/new': typeof AuthenticatedPekerjaanNewRoute
  '/_authenticated/penerima/new': typeof AuthenticatedPenerimaNewRoute
  '/_authenticated/permissions/new': typeof AuthenticatedPermissionsNewRoute
  '/_authenticated/roles/new': typeof AuthenticatedRolesNewRoute
  '/_authenticated/route-permissions/new': typeof AuthenticatedRoutePermissionsNewRoute
  '/_authenticated/users/new': typeof AuthenticatedUsersNewRoute
  '/_authenticated/berkas/': typeof AuthenticatedBerkasIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/desa/': typeof AuthenticatedDesaIndexRoute
  '/_authenticated/foto/': typeof AuthenticatedFotoIndexRoute
  '/_authenticated/kecamatan/': typeof AuthenticatedKecamatanIndexRoute
  '/_authenticated/kegiatan/': typeof AuthenticatedKegiatanIndexRoute
  '/_authenticated/kontrak/': typeof AuthenticatedKontrakIndexRoute
  '/_authenticated/menu-permissions/': typeof AuthenticatedMenuPermissionsIndexRoute
  '/_authenticated/output/': typeof AuthenticatedOutputIndexRoute
  '/_authenticated/pekerjaan/': typeof AuthenticatedPekerjaanIndexRoute
  '/_authenticated/penerima/': typeof AuthenticatedPenerimaIndexRoute
  '/_authenticated/route-permissions/': typeof AuthenticatedRoutePermissionsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/berkas/$id/edit': typeof AuthenticatedBerkasIdEditRoute
  '/_authenticated/desa/$id/edit': typeof AuthenticatedDesaIdEditRoute
  '/_authenticated/foto/$id/edit': typeof AuthenticatedFotoIdEditRoute
  '/_authenticated/kecamatan/$id/edit': typeof AuthenticatedKecamatanIdEditRoute
  '/_authenticated/kegiatan-role/$id/edit': typeof AuthenticatedKegiatanRoleIdEditRoute
  '/_authenticated/kegiatan/$id/edit': typeof AuthenticatedKegiatanIdEditRoute
  '/_authenticated/kontrak/$id/edit': typeof AuthenticatedKontrakIdEditRoute
  '/_authenticated/menu-permissions/$id/edit': typeof AuthenticatedMenuPermissionsIdEditRoute
  '/_authenticated/output/$id/edit': typeof AuthenticatedOutputIdEditRoute
  '/_authenticated/pekerjaan/$id/edit': typeof AuthenticatedPekerjaanIdEditRoute
  '/_authenticated/pekerjaan/$id/progress': typeof AuthenticatedPekerjaanIdProgressRoute
  '/_authenticated/penerima/$id/edit': typeof AuthenticatedPenerimaIdEditRoute
  '/_authenticated/permissions/$id/edit': typeof AuthenticatedPermissionsIdEditRoute
  '/_authenticated/roles/$id/edit': typeof AuthenticatedRolesIdEditRoute
  '/_authenticated/route-permissions/$id/edit': typeof AuthenticatedRoutePermissionsIdEditRoute
  '/_authenticated/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/oauth-callback'
    | '/sign-in'
    | '/'
    | '/berkas/new'
    | '/desa/new'
    | '/foto/new'
    | '/kecamatan/new'
    | '/kegiatan-role/new'
    | '/kegiatan/new'
    | '/kontrak/new'
    | '/menu-permissions/new'
    | '/output/new'
    | '/pekerjaan/$id'
    | '/pekerjaan/new'
    | '/penerima/new'
    | '/permissions/new'
    | '/roles/new'
    | '/route-permissions/new'
    | '/users/new'
    | '/berkas'
    | '/chat'
    | '/desa'
    | '/foto'
    | '/kecamatan'
    | '/kegiatan'
    | '/kontrak'
    | '/menu-permissions'
    | '/output'
    | '/pekerjaan'
    | '/penerima'
    | '/route-permissions'
    | '/settings'
    | '/berkas/$id/edit'
    | '/desa/$id/edit'
    | '/foto/$id/edit'
    | '/kecamatan/$id/edit'
    | '/kegiatan-role/$id/edit'
    | '/kegiatan/$id/edit'
    | '/kontrak/$id/edit'
    | '/menu-permissions/$id/edit'
    | '/output/$id/edit'
    | '/pekerjaan/$id/edit'
    | '/pekerjaan/$id/progress'
    | '/penerima/$id/edit'
    | '/permissions/$id/edit'
    | '/roles/$id/edit'
    | '/route-permissions/$id/edit'
    | '/users/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/oauth-callback'
    | '/sign-in'
    | '/'
    | '/berkas/new'
    | '/desa/new'
    | '/foto/new'
    | '/kecamatan/new'
    | '/kegiatan-role/new'
    | '/kegiatan/new'
    | '/kontrak/new'
    | '/menu-permissions/new'
    | '/output/new'
    | '/pekerjaan/$id'
    | '/pekerjaan/new'
    | '/penerima/new'
    | '/permissions/new'
    | '/roles/new'
    | '/route-permissions/new'
    | '/users/new'
    | '/berkas'
    | '/chat'
    | '/desa'
    | '/foto'
    | '/kecamatan'
    | '/kegiatan'
    | '/kontrak'
    | '/menu-permissions'
    | '/output'
    | '/pekerjaan'
    | '/penerima'
    | '/route-permissions'
    | '/settings'
    | '/berkas/$id/edit'
    | '/desa/$id/edit'
    | '/foto/$id/edit'
    | '/kecamatan/$id/edit'
    | '/kegiatan-role/$id/edit'
    | '/kegiatan/$id/edit'
    | '/kontrak/$id/edit'
    | '/menu-permissions/$id/edit'
    | '/output/$id/edit'
    | '/pekerjaan/$id/edit'
    | '/pekerjaan/$id/progress'
    | '/penerima/$id/edit'
    | '/permissions/$id/edit'
    | '/roles/$id/edit'
    | '/route-permissions/$id/edit'
    | '/users/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/oauth-callback'
    | '/sign-in'
    | '/_authenticated/'
    | '/_authenticated/berkas/new'
    | '/_authenticated/desa/new'
    | '/_authenticated/foto/new'
    | '/_authenticated/kecamatan/new'
    | '/_authenticated/kegiatan-role/new'
    | '/_authenticated/kegiatan/new'
    | '/_authenticated/kontrak/new'
    | '/_authenticated/menu-permissions/new'
    | '/_authenticated/output/new'
    | '/_authenticated/pekerjaan/$id'
    | '/_authenticated/pekerjaan/new'
    | '/_authenticated/penerima/new'
    | '/_authenticated/permissions/new'
    | '/_authenticated/roles/new'
    | '/_authenticated/route-permissions/new'
    | '/_authenticated/users/new'
    | '/_authenticated/berkas/'
    | '/_authenticated/chat/'
    | '/_authenticated/desa/'
    | '/_authenticated/foto/'
    | '/_authenticated/kecamatan/'
    | '/_authenticated/kegiatan/'
    | '/_authenticated/kontrak/'
    | '/_authenticated/menu-permissions/'
    | '/_authenticated/output/'
    | '/_authenticated/pekerjaan/'
    | '/_authenticated/penerima/'
    | '/_authenticated/route-permissions/'
    | '/_authenticated/settings/'
    | '/_authenticated/berkas/$id/edit'
    | '/_authenticated/desa/$id/edit'
    | '/_authenticated/foto/$id/edit'
    | '/_authenticated/kecamatan/$id/edit'
    | '/_authenticated/kegiatan-role/$id/edit'
    | '/_authenticated/kegiatan/$id/edit'
    | '/_authenticated/kontrak/$id/edit'
    | '/_authenticated/menu-permissions/$id/edit'
    | '/_authenticated/output/$id/edit'
    | '/_authenticated/pekerjaan/$id/edit'
    | '/_authenticated/pekerjaan/$id/progress'
    | '/_authenticated/penerima/$id/edit'
    | '/_authenticated/permissions/$id/edit'
    | '/_authenticated/roles/$id/edit'
    | '/_authenticated/route-permissions/$id/edit'
    | '/_authenticated/users/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OauthCallbackRoute: typeof OauthCallbackRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/route-permissions/': {
      id: '/_authenticated/route-permissions/'
      path: '/route-permissions'
      fullPath: '/route-permissions'
      preLoaderRoute: typeof AuthenticatedRoutePermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/penerima/': {
      id: '/_authenticated/penerima/'
      path: '/penerima'
      fullPath: '/penerima'
      preLoaderRoute: typeof AuthenticatedPenerimaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pekerjaan/': {
      id: '/_authenticated/pekerjaan/'
      path: '/pekerjaan'
      fullPath: '/pekerjaan'
      preLoaderRoute: typeof AuthenticatedPekerjaanIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/output/': {
      id: '/_authenticated/output/'
      path: '/output'
      fullPath: '/output'
      preLoaderRoute: typeof AuthenticatedOutputIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu-permissions/': {
      id: '/_authenticated/menu-permissions/'
      path: '/menu-permissions'
      fullPath: '/menu-permissions'
      preLoaderRoute: typeof AuthenticatedMenuPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kontrak/': {
      id: '/_authenticated/kontrak/'
      path: '/kontrak'
      fullPath: '/kontrak'
      preLoaderRoute: typeof AuthenticatedKontrakIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kegiatan/': {
      id: '/_authenticated/kegiatan/'
      path: '/kegiatan'
      fullPath: '/kegiatan'
      preLoaderRoute: typeof AuthenticatedKegiatanIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kecamatan/': {
      id: '/_authenticated/kecamatan/'
      path: '/kecamatan'
      fullPath: '/kecamatan'
      preLoaderRoute: typeof AuthenticatedKecamatanIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/foto/': {
      id: '/_authenticated/foto/'
      path: '/foto'
      fullPath: '/foto'
      preLoaderRoute: typeof AuthenticatedFotoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/desa/': {
      id: '/_authenticated/desa/'
      path: '/desa'
      fullPath: '/desa'
      preLoaderRoute: typeof AuthenticatedDesaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/berkas/': {
      id: '/_authenticated/berkas/'
      path: '/berkas'
      fullPath: '/berkas'
      preLoaderRoute: typeof AuthenticatedBerkasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/new': {
      id: '/_authenticated/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/route-permissions/new': {
      id: '/_authenticated/route-permissions/new'
      path: '/route-permissions/new'
      fullPath: '/route-permissions/new'
      preLoaderRoute: typeof AuthenticatedRoutePermissionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/new': {
      id: '/_authenticated/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof AuthenticatedRolesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permissions/new': {
      id: '/_authenticated/permissions/new'
      path: '/permissions/new'
      fullPath: '/permissions/new'
      preLoaderRoute: typeof AuthenticatedPermissionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/penerima/new': {
      id: '/_authenticated/penerima/new'
      path: '/penerima/new'
      fullPath: '/penerima/new'
      preLoaderRoute: typeof AuthenticatedPenerimaNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pekerjaan/new': {
      id: '/_authenticated/pekerjaan/new'
      path: '/pekerjaan/new'
      fullPath: '/pekerjaan/new'
      preLoaderRoute: typeof AuthenticatedPekerjaanNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pekerjaan/$id': {
      id: '/_authenticated/pekerjaan/$id'
      path: '/pekerjaan/$id'
      fullPath: '/pekerjaan/$id'
      preLoaderRoute: typeof AuthenticatedPekerjaanIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/output/new': {
      id: '/_authenticated/output/new'
      path: '/output/new'
      fullPath: '/output/new'
      preLoaderRoute: typeof AuthenticatedOutputNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu-permissions/new': {
      id: '/_authenticated/menu-permissions/new'
      path: '/menu-permissions/new'
      fullPath: '/menu-permissions/new'
      preLoaderRoute: typeof AuthenticatedMenuPermissionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kontrak/new': {
      id: '/_authenticated/kontrak/new'
      path: '/kontrak/new'
      fullPath: '/kontrak/new'
      preLoaderRoute: typeof AuthenticatedKontrakNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kegiatan/new': {
      id: '/_authenticated/kegiatan/new'
      path: '/kegiatan/new'
      fullPath: '/kegiatan/new'
      preLoaderRoute: typeof AuthenticatedKegiatanNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kegiatan-role/new': {
      id: '/_authenticated/kegiatan-role/new'
      path: '/kegiatan-role/new'
      fullPath: '/kegiatan-role/new'
      preLoaderRoute: typeof AuthenticatedKegiatanRoleNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kecamatan/new': {
      id: '/_authenticated/kecamatan/new'
      path: '/kecamatan/new'
      fullPath: '/kecamatan/new'
      preLoaderRoute: typeof AuthenticatedKecamatanNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/foto/new': {
      id: '/_authenticated/foto/new'
      path: '/foto/new'
      fullPath: '/foto/new'
      preLoaderRoute: typeof AuthenticatedFotoNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/desa/new': {
      id: '/_authenticated/desa/new'
      path: '/desa/new'
      fullPath: '/desa/new'
      preLoaderRoute: typeof AuthenticatedDesaNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/berkas/new': {
      id: '/_authenticated/berkas/new'
      path: '/berkas/new'
      fullPath: '/berkas/new'
      preLoaderRoute: typeof AuthenticatedBerkasNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$id/edit': {
      id: '/_authenticated/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof AuthenticatedUsersIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/route-permissions/$id/edit': {
      id: '/_authenticated/route-permissions/$id/edit'
      path: '/route-permissions/$id/edit'
      fullPath: '/route-permissions/$id/edit'
      preLoaderRoute: typeof AuthenticatedRoutePermissionsIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/$id/edit': {
      id: '/_authenticated/roles/$id/edit'
      path: '/roles/$id/edit'
      fullPath: '/roles/$id/edit'
      preLoaderRoute: typeof AuthenticatedRolesIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permissions/$id/edit': {
      id: '/_authenticated/permissions/$id/edit'
      path: '/permissions/$id/edit'
      fullPath: '/permissions/$id/edit'
      preLoaderRoute: typeof AuthenticatedPermissionsIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/penerima/$id/edit': {
      id: '/_authenticated/penerima/$id/edit'
      path: '/penerima/$id/edit'
      fullPath: '/penerima/$id/edit'
      preLoaderRoute: typeof AuthenticatedPenerimaIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pekerjaan/$id/progress': {
      id: '/_authenticated/pekerjaan/$id/progress'
      path: '/progress'
      fullPath: '/pekerjaan/$id/progress'
      preLoaderRoute: typeof AuthenticatedPekerjaanIdProgressRouteImport
      parentRoute: typeof AuthenticatedPekerjaanIdRoute
    }
    '/_authenticated/pekerjaan/$id/edit': {
      id: '/_authenticated/pekerjaan/$id/edit'
      path: '/edit'
      fullPath: '/pekerjaan/$id/edit'
      preLoaderRoute: typeof AuthenticatedPekerjaanIdEditRouteImport
      parentRoute: typeof AuthenticatedPekerjaanIdRoute
    }
    '/_authenticated/output/$id/edit': {
      id: '/_authenticated/output/$id/edit'
      path: '/output/$id/edit'
      fullPath: '/output/$id/edit'
      preLoaderRoute: typeof AuthenticatedOutputIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu-permissions/$id/edit': {
      id: '/_authenticated/menu-permissions/$id/edit'
      path: '/menu-permissions/$id/edit'
      fullPath: '/menu-permissions/$id/edit'
      preLoaderRoute: typeof AuthenticatedMenuPermissionsIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kontrak/$id/edit': {
      id: '/_authenticated/kontrak/$id/edit'
      path: '/kontrak/$id/edit'
      fullPath: '/kontrak/$id/edit'
      preLoaderRoute: typeof AuthenticatedKontrakIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kegiatan/$id/edit': {
      id: '/_authenticated/kegiatan/$id/edit'
      path: '/kegiatan/$id/edit'
      fullPath: '/kegiatan/$id/edit'
      preLoaderRoute: typeof AuthenticatedKegiatanIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kegiatan-role/$id/edit': {
      id: '/_authenticated/kegiatan-role/$id/edit'
      path: '/kegiatan-role/$id/edit'
      fullPath: '/kegiatan-role/$id/edit'
      preLoaderRoute: typeof AuthenticatedKegiatanRoleIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kecamatan/$id/edit': {
      id: '/_authenticated/kecamatan/$id/edit'
      path: '/kecamatan/$id/edit'
      fullPath: '/kecamatan/$id/edit'
      preLoaderRoute: typeof AuthenticatedKecamatanIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/foto/$id/edit': {
      id: '/_authenticated/foto/$id/edit'
      path: '/foto/$id/edit'
      fullPath: '/foto/$id/edit'
      preLoaderRoute: typeof AuthenticatedFotoIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/desa/$id/edit': {
      id: '/_authenticated/desa/$id/edit'
      path: '/desa/$id/edit'
      fullPath: '/desa/$id/edit'
      preLoaderRoute: typeof AuthenticatedDesaIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/berkas/$id/edit': {
      id: '/_authenticated/berkas/$id/edit'
      path: '/berkas/$id/edit'
      fullPath: '/berkas/$id/edit'
      preLoaderRoute: typeof AuthenticatedBerkasIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedPekerjaanIdRouteChildren {
  AuthenticatedPekerjaanIdEditRoute: typeof AuthenticatedPekerjaanIdEditRoute
  AuthenticatedPekerjaanIdProgressRoute: typeof AuthenticatedPekerjaanIdProgressRoute
}

const AuthenticatedPekerjaanIdRouteChildren: AuthenticatedPekerjaanIdRouteChildren =
  {
    AuthenticatedPekerjaanIdEditRoute: AuthenticatedPekerjaanIdEditRoute,
    AuthenticatedPekerjaanIdProgressRoute:
      AuthenticatedPekerjaanIdProgressRoute,
  }

const AuthenticatedPekerjaanIdRouteWithChildren =
  AuthenticatedPekerjaanIdRoute._addFileChildren(
    AuthenticatedPekerjaanIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBerkasNewRoute: typeof AuthenticatedBerkasNewRoute
  AuthenticatedDesaNewRoute: typeof AuthenticatedDesaNewRoute
  AuthenticatedFotoNewRoute: typeof AuthenticatedFotoNewRoute
  AuthenticatedKecamatanNewRoute: typeof AuthenticatedKecamatanNewRoute
  AuthenticatedKegiatanRoleNewRoute: typeof AuthenticatedKegiatanRoleNewRoute
  AuthenticatedKegiatanNewRoute: typeof AuthenticatedKegiatanNewRoute
  AuthenticatedKontrakNewRoute: typeof AuthenticatedKontrakNewRoute
  AuthenticatedMenuPermissionsNewRoute: typeof AuthenticatedMenuPermissionsNewRoute
  AuthenticatedOutputNewRoute: typeof AuthenticatedOutputNewRoute
  AuthenticatedPekerjaanIdRoute: typeof AuthenticatedPekerjaanIdRouteWithChildren
  AuthenticatedPekerjaanNewRoute: typeof AuthenticatedPekerjaanNewRoute
  AuthenticatedPenerimaNewRoute: typeof AuthenticatedPenerimaNewRoute
  AuthenticatedPermissionsNewRoute: typeof AuthenticatedPermissionsNewRoute
  AuthenticatedRolesNewRoute: typeof AuthenticatedRolesNewRoute
  AuthenticatedRoutePermissionsNewRoute: typeof AuthenticatedRoutePermissionsNewRoute
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute
  AuthenticatedBerkasIndexRoute: typeof AuthenticatedBerkasIndexRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedDesaIndexRoute: typeof AuthenticatedDesaIndexRoute
  AuthenticatedFotoIndexRoute: typeof AuthenticatedFotoIndexRoute
  AuthenticatedKecamatanIndexRoute: typeof AuthenticatedKecamatanIndexRoute
  AuthenticatedKegiatanIndexRoute: typeof AuthenticatedKegiatanIndexRoute
  AuthenticatedKontrakIndexRoute: typeof AuthenticatedKontrakIndexRoute
  AuthenticatedMenuPermissionsIndexRoute: typeof AuthenticatedMenuPermissionsIndexRoute
  AuthenticatedOutputIndexRoute: typeof AuthenticatedOutputIndexRoute
  AuthenticatedPekerjaanIndexRoute: typeof AuthenticatedPekerjaanIndexRoute
  AuthenticatedPenerimaIndexRoute: typeof AuthenticatedPenerimaIndexRoute
  AuthenticatedRoutePermissionsIndexRoute: typeof AuthenticatedRoutePermissionsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedBerkasIdEditRoute: typeof AuthenticatedBerkasIdEditRoute
  AuthenticatedDesaIdEditRoute: typeof AuthenticatedDesaIdEditRoute
  AuthenticatedFotoIdEditRoute: typeof AuthenticatedFotoIdEditRoute
  AuthenticatedKecamatanIdEditRoute: typeof AuthenticatedKecamatanIdEditRoute
  AuthenticatedKegiatanRoleIdEditRoute: typeof AuthenticatedKegiatanRoleIdEditRoute
  AuthenticatedKegiatanIdEditRoute: typeof AuthenticatedKegiatanIdEditRoute
  AuthenticatedKontrakIdEditRoute: typeof AuthenticatedKontrakIdEditRoute
  AuthenticatedMenuPermissionsIdEditRoute: typeof AuthenticatedMenuPermissionsIdEditRoute
  AuthenticatedOutputIdEditRoute: typeof AuthenticatedOutputIdEditRoute
  AuthenticatedPenerimaIdEditRoute: typeof AuthenticatedPenerimaIdEditRoute
  AuthenticatedPermissionsIdEditRoute: typeof AuthenticatedPermissionsIdEditRoute
  AuthenticatedRolesIdEditRoute: typeof AuthenticatedRolesIdEditRoute
  AuthenticatedRoutePermissionsIdEditRoute: typeof AuthenticatedRoutePermissionsIdEditRoute
  AuthenticatedUsersIdEditRoute: typeof AuthenticatedUsersIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBerkasNewRoute: AuthenticatedBerkasNewRoute,
  AuthenticatedDesaNewRoute: AuthenticatedDesaNewRoute,
  AuthenticatedFotoNewRoute: AuthenticatedFotoNewRoute,
  AuthenticatedKecamatanNewRoute: AuthenticatedKecamatanNewRoute,
  AuthenticatedKegiatanRoleNewRoute: AuthenticatedKegiatanRoleNewRoute,
  AuthenticatedKegiatanNewRoute: AuthenticatedKegiatanNewRoute,
  AuthenticatedKontrakNewRoute: AuthenticatedKontrakNewRoute,
  AuthenticatedMenuPermissionsNewRoute: AuthenticatedMenuPermissionsNewRoute,
  AuthenticatedOutputNewRoute: AuthenticatedOutputNewRoute,
  AuthenticatedPekerjaanIdRoute: AuthenticatedPekerjaanIdRouteWithChildren,
  AuthenticatedPekerjaanNewRoute: AuthenticatedPekerjaanNewRoute,
  AuthenticatedPenerimaNewRoute: AuthenticatedPenerimaNewRoute,
  AuthenticatedPermissionsNewRoute: AuthenticatedPermissionsNewRoute,
  AuthenticatedRolesNewRoute: AuthenticatedRolesNewRoute,
  AuthenticatedRoutePermissionsNewRoute: AuthenticatedRoutePermissionsNewRoute,
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedBerkasIndexRoute: AuthenticatedBerkasIndexRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedDesaIndexRoute: AuthenticatedDesaIndexRoute,
  AuthenticatedFotoIndexRoute: AuthenticatedFotoIndexRoute,
  AuthenticatedKecamatanIndexRoute: AuthenticatedKecamatanIndexRoute,
  AuthenticatedKegiatanIndexRoute: AuthenticatedKegiatanIndexRoute,
  AuthenticatedKontrakIndexRoute: AuthenticatedKontrakIndexRoute,
  AuthenticatedMenuPermissionsIndexRoute:
    AuthenticatedMenuPermissionsIndexRoute,
  AuthenticatedOutputIndexRoute: AuthenticatedOutputIndexRoute,
  AuthenticatedPekerjaanIndexRoute: AuthenticatedPekerjaanIndexRoute,
  AuthenticatedPenerimaIndexRoute: AuthenticatedPenerimaIndexRoute,
  AuthenticatedRoutePermissionsIndexRoute:
    AuthenticatedRoutePermissionsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedBerkasIdEditRoute: AuthenticatedBerkasIdEditRoute,
  AuthenticatedDesaIdEditRoute: AuthenticatedDesaIdEditRoute,
  AuthenticatedFotoIdEditRoute: AuthenticatedFotoIdEditRoute,
  AuthenticatedKecamatanIdEditRoute: AuthenticatedKecamatanIdEditRoute,
  AuthenticatedKegiatanRoleIdEditRoute: AuthenticatedKegiatanRoleIdEditRoute,
  AuthenticatedKegiatanIdEditRoute: AuthenticatedKegiatanIdEditRoute,
  AuthenticatedKontrakIdEditRoute: AuthenticatedKontrakIdEditRoute,
  AuthenticatedMenuPermissionsIdEditRoute:
    AuthenticatedMenuPermissionsIdEditRoute,
  AuthenticatedOutputIdEditRoute: AuthenticatedOutputIdEditRoute,
  AuthenticatedPenerimaIdEditRoute: AuthenticatedPenerimaIdEditRoute,
  AuthenticatedPermissionsIdEditRoute: AuthenticatedPermissionsIdEditRoute,
  AuthenticatedRolesIdEditRoute: AuthenticatedRolesIdEditRoute,
  AuthenticatedRoutePermissionsIdEditRoute:
    AuthenticatedRoutePermissionsIdEditRoute,
  AuthenticatedUsersIdEditRoute: AuthenticatedUsersIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OauthCallbackRoute: OauthCallbackRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
